stages:

  remove_corrupted_images:
    cmd: python src/remove_corrupted_images.py data/inputs
    deps:
    - data/inputs
    - src/remove_corrupted_images.py
    outs:
    - data/intermediate/remove_corrupted_images

  remove_dark_and_bright_images:
    cmd: python src/remove_dark_and_bright_images.py data/intermediate/remove_corrupted_images
    deps:
      - data/intermediate/remove_corrupted_images
      - src/remove_dark_and_bright_images.py
    params:
      - remove_dark_and_bright_images.dark_image_threshold
      - remove_dark_and_bright_images.bright_image_threshold
    outs:
      - data/intermediate/remove_dark_and_bright_images

  classify_day_night_and_foggy_images:
    cmd: python src/classify_day_night_and_foggy_images.py data/intermediate/remove_dark_and_bright_images
    deps:
      - data/intermediate/remove_dark_and_bright_images
      - src/classify_day_night_and_foggy_images.py
    params:
      - classify_day_night_and_foggy_images.day_night_image_threshold
      - classify_day_night_and_foggy_images.fog_image_threshold
    outs:
      - data/outputs/day_images/foggy
      - data/outputs/day_images/sharp
      - data/outputs/night_images/foggy
      - data/outputs/night_images/sharp
